name: coworkout deployment actions
run-name: Main branch
on: [push]
jobs:
  build_and_deploy:
    runs-on: 'ubuntu-latest'
    env:
      working-directory: './functions'

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm ci
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/720803368237/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'develop@coworkout-20230409.iam.gserviceaccount.com'

    - name: 'Init GCP'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: 'Use gcloud'
      run: 'gcloud info'
    - id: 'deploy_api'
      name: 'Deploy api'
      run: |
        npm run build &&
        gcloud functions deploy api \
          --runtime=nodejs16 \
          --region=us-central1 \
          --source=./dist \
          --memory=128MB \
          --entry-point=api \
          --trigger-http \
          --allow-unauthenticated \
          --max-instances=2
    
    - id: 'deploy_cron'
      name: 'Deploy cron'
      run: |
        npm run build &&
        gcloud functions deploy cron \
          --runtime=nodejs16 \
          --region=us-central1 \
          --source=./dist \
          --memory=128MB \
          --entry-point=cron \
          --trigger-http \
          --allow-unauthenticated \
          --max-instances=2

    # - id: 'deploy'
    #   uses: 'google-github-actions/deploy-cloud-functions@v1'
    #   with:
    #     project_id: 'coworkout-20230409'
    #     name: 'fn'
    #     source_dir: './functions'
    #     entry_point: 'api'
    #     memory_mb: '128'
    #     region: 'us-central1'
    #     runtime: 'nodejs16'
    #     max_instances: 2

    # - id: 'test'
    #   run: 'curl "${{ steps.deploy.outputs.url }}"'